# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kuru

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Ki3ie
    name: kuru
